Cleanup and fix configuration options
unikraft/lib-lwip pull request #26
Opened 2022-11-23 09:12 UTC by mschlumpp

The corresponding Unikraft config has a `CONFIG_` prefix that won't be picked up by the LWIP source code.
This also removes two unused configuration options.

2023-01-29 15:18 UTC, razvand commented
Hi, @mschlumpp. This looks good to me. I'm guessing something similar should happen to other options in `Config.uk` such as `LWIP_TCP_TIMESTAMPS`. I didn't find any other option similar to these two (`LWIP_TCP_KEEPALIVE` and `LWIP_TCP_TIMESTAMPS`), but I also didn't do a deep dig.

2023-02-01 00:24 UTC, RaduNichita requested changes
Hi, 

It also seems ok to me, but please change the commit message and include at the beginning of each one the filename. (e.g: `lwipopts.h: Pass TCP keep-alive config define to LWIP code`)

2023-02-01 13:32 UTC, mschlumpp commented
@RaduNichita as far as I know we don't have any guideline to include the specific modified source files in the commit message. We also don't do that in the main repository and therefore it would be inconsistent with the guidelines there.

2023-02-02 21:04 UTC, razvand commented
@RaduNichita, I agree with @mschlumpp. His commit message format is OK. Please approve / review it and I will then do it myself.

2023-02-02 21:08 UTC, RaduNichita approved these changes
OK, so besides that, all is good with me. Thanks, @mschlumpp 💯 

Reviewed-by: Radu Nichita <radunichita99@gmail.com>

2023-02-03 15:01 UTC, razvand approved these changes
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2023-02-03 22:51 UTC, closed without merging