Various smaller fixes
unikraft/lib-lwip pull request #46
Opened 2024-01-30 09:07 UTC by mschlumpp

These were primarily motivated by the glibc DNS resolver. The resolver code relies on being able to successfully set socket options, which are not available on LWIP.
Also the resolver sends multiple packets at once, which requires queuing packets until the initial ARP request is answered.

2024-02-01 15:00 UTC, StefanJum requested changes
@mschlumpp  please use the same email address for the commiter and author, all good otherwise.

2024-02-02 10:08 UTC, mschlumpp commented
Done

2024-02-02 13:55 UTC, StefanJum approved these changes
All good now, thanks.
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2024-02-02 14:38 UTC, Mihnea0Firoiu approved these changes
Looks good.
Reviewed-by: Mihnea Firoiu <mihneafiroiu0@gmail.com>

2024-02-06 21:52 UTC, razvand approved these changes
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2024-02-06 21:53 UTC, merged