Indicate EPOLLRDHUP when the peer closed the connection
unikraft/lib-lwip pull request #55
Opened 2024-04-15 12:12 UTC by mschlumpp

The RDHUP event is used by nginx to reduce the amount of syscalls it has to do by knowing whether a EOF is coming up. Not setting this event will cause nginx to hang with fcgi_pass configurations.

2024-04-26 16:44 UTC, michpappas requested changes

2024-04-26 16:44 UTC, michpappas commented on sockets.c
> +                if (sock->conn->pcb.tcp->state == CLOSE_WAIT)
This one needs to additionally check if `sock->conn.pcb.tcp == NULL` as `pcb` is freed by lwip if the connection is reset: https://github.com/unikraft/fork-lwip/blob/UNIKRAFT-2_1_x/src/core/tcp_in.c#L442

2024-05-31 09:52 UTC, michpappas approved these changes
Reviewed-by: Michalis Pappas <michalis@unikraft.io>

2024-05-31 14:27 UTC, eduardvintila approved these changes
Thanks.

Reviewed-by: Eduard Vintilă <eduard.vintila47@gmail.com>

2024-05-31 15:57 UTC, mariapana approved these changes
All good!

Reviewed-by: Maria Pană <maria.pana4@gmail.com>

2024-05-31 17:48 UTC, razvand approved these changes
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2024-05-31 17:50 UTC, merged