Fix #59, invalid pointer for dns addr in gcc14
unikraft/lib-lwip pull request #60
Opened 2024-12-08 11:11 UTC by cluosh

The invalid pointer warning becomes an error in gcc14, and it turns out it's actually an invalid pointer, because it expects a pointer to a struct with a type tag and not just the IPv4 address.

2024-12-17 20:22 UTC, andreittr requested changes
Thanks for the patch, good catch! Code looks all in order, I've got just small comments re commit formatting:

Commit titles ideally are understandable with minimal context, so references to github issues should be avoided. Also gcc14 is secondary to the problem being solved and can thus be left only in the description (the bug you're fixing _is_ the invalid struct/pointer use, gcc14 only helped you catch it).

So something like `Fix invalid pointer for dns` would be simpler and better suited.

Also, please add a line at the end of your commit in the form of
`Signed-off-by: Your Name <your@email.addr>`
`git` generates this automatically if you pass `-s` when doing the commit. You can find examples in previous commits on this repo.

In general if you want to reference bugs/issues, it's best to use the standard machine-parsable github tag next to the `Signed-off-by` line like
`Github-fixes: #59 `

2024-12-17 21:50 UTC, cluosh commented
Thanks for the review, I updated the commit message!

2024-12-18 08:10 UTC, andreittr approved these changes
Looks good, thanks!

Approved-by: Andrei Tatar <andrei@unikraft.io>

2024-12-19 15:13 UTC, razvand approved these changes
Reviewed-by: Razvan Deaconescu <razvand@unikraft.io>
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2024-12-19 15:27 UTC, merged